imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: true
    bundles:        ['CMSStoreBundle']
    java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# firewall
fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: CMS\StoreBundle\Entity\User

# tinymce
stfalcon_tinymce:
    include_jquery: true
    tinymce_jquery: true
    theme:
        simple:
          dialog_type: "modal"
          mode: "textareas"
          theme: "advanced"
          theme_advanced_buttons1: bold,italic,underline,strikethrough,formatselect,justifyleft,justifycenter,justifyright,justifyfull,|,cut,copy,paste,pastetext,pasteword,removeformat,|,bullist,numlist,|,undo,redo,|,link,unlink,image,insertimage
          theme_advanced_buttons2: ""
          theme_advanced_buttons3: ""
          theme_advanced_toolbar_location: "top"
          theme_advanced_toolbar_align: "left"
          theme_advanced_statusbar_location: "bottom"
          plugins: "fullscreen"
          theme_advanced_buttons1_add: "fullscreen"
          relative_urls: false
          file_browser_callback: "MadFileBrowser"
knp_paginator:
    page_range: 2
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: false
    template:
        pagination: CMSAdminBundle:Pagination:sliding.html.twig
        sortable: CMSAdminBundle:Pagination:sortable_link.html.twig