parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: guerr543_cms
    database_user: guerr543_cms
    database_password: gdasaida3
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 6866a1c9f651c712b8c130d3ef351e110a45d012
    database_path: null
