parameters:
    database_driver: pdo_mysql
    database_host: mysql.agenciatamandua.com.br
    database_port: null
    database_name: cms
    database_user: agenciatamandu04
    database_password: tamandua123
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 6866a1c9f651c712b8c130d3ef351e110a45d012
    database_path: null

